
rep0: 'a' 'b'* 'c'

%%

let failed = ref false

let () =
  let is_match = function Ok (_,(_,_,len), _) -> len=0 | Error _ -> false in
  let test (rule, input, expected) =
    let result = rule (string_view_of_string input) in
    if is_match result <> expected
    then (
      failed := true;
      Printf.eprintf "Expected \"%s\" to%s match, but it didn't!"
        input (if expected then "" else " not" )
      )
    else ()
  in
  List.iter test [
    rep0, "ac", true;
    rep0, "abc", true;
    rep0, "abbc", true;
    rep0, "abbbc", true;
  ];
  if !failed then exit 1 else exit 0

