
parse: v1=a ' '* "and" ' '* v2=b { v1 ^ v2 }
;
a: "a"
;
b: "b"
;

seq2: v1=letter { Printf.sprintf "(%c)" v1 } v2=letter     { v2 }
;
letter: [A-Za-z]
;

%%

let () =
  let input = string_view_of_string "a and b" in
  match (parse input) with
  | Ok ("ab", (_, _, len), _) -> exit 0
  | Ok (value, _, _) ->
      (Printf.eprintf "Expected match, after action, to be \"ab\", actual: %s"
        value;
       exit 1)
  | Error msg -> (Printf.eprintf "%s" msg)

